// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU9_ncs4QnQJ6936lXpGtOIPy0eYQC_MQ',
    appId: '1:358911552570:android:69aa92dd3ffb7a90d05903',
    messagingSenderId: '358911552570',
    projectId: 'nail-artists-hub',
    databaseURL: 'https://nail-artists-hub-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nail-artists-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9_L2qrsoHAuRpq057LM812gg7GYih_6o',
    appId: '1:358911552570:ios:772af844052be606d05903',
    messagingSenderId: '358911552570',
    projectId: 'nail-artists-hub',
    databaseURL: 'https://nail-artists-hub-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nail-artists-hub.appspot.com',
    iosClientId: '358911552570-ee47pcc2rc8j4lvsmq8e7filcr6gaptf.apps.googleusercontent.com',
    iosBundleId: 'com.example.nailArtistsHub',
  );
}
